import "../assets/css/main.css";
import { MoviesProvider } from "../componenets/MoviesContext";
import { AuthProvider } from "../componenets/login/authcontext";
import Header from "../componenets/Header";
import Footer from "../componenets/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <MoviesProvider>
            <Header />
            {children}
            <Footer />
          </MoviesProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
